import os

# pyrefly: ignore [missing-import]
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

def train():
    # Training Data (approx. 320 entries across 10 categories)
    data = [
        # Electrical
        ("the fan in room 302 is not working", "Electrical"),
        ("light in the corridor is flickering and needs replacement", "Electrical"),
        ("power outlet in the library is damaged and not supplying electricity", "Electrical"),
        ("the air conditioner in laboratory 1 is not cooling at all", "Electrical"),
        ("burnt switch board in the main block", "Electrical"),
        ("short circuit in the hostel room 405", "Electrical"),
        ("projector power cable is cut and not turning on", "Electrical"),
        ("fuse is blown in the mechanical workshop", "Electrical"),
        ("loose wires are hanging from the ceiling in block c", "Electrical"),
        ("entire classroom has no electricity, fans and lights are off", "Electrical"),
        ("ac remote is missing or broken in the seminar hall", "Electrical"),
        ("flickering led lights in block b class 101", "Electrical"),
        ("electric shock when touching the metal table in computer lab", "Electrical"),
        ("exhaust fan in the hostel restroom is making loud noises", "Electrical"),
        ("no electrical backup when the main power cuts", "Electrical"),
        ("water heater in hostel shower room has shorted out", "Electrical"),
        ("corridor light switch is broken", "Electrical"),
        ("ups battery backup in the administrative office is beep sound", "Electrical"),
        ("street light near college playground is dead", "Electrical"),
        ("lab system power buttons are broken", "Electrical"),
        ("extension cord sparking in electronics lab", "Electrical"),
        ("electric board has exposed copper wires", "Electrical"),
        ("the ac is leaking water inside the classroom", "Electrical"),
        ("socket pins are bent and plugs won't fit", "Electrical"),
        ("the tube light in the girls washroom is dead", "Electrical"),
        ("ceiling fan regulator is stuck at low speed", "Electrical"),
        ("fuses are constantly tripping in physics lab", "Electrical"),
        ("smart board power adapter is missing", "Electrical"),
        ("wall sockets are loose in staff room", "Electrical"),
        ("power fluctuation destroyed the server motherboard", "Electrical"),

        # Water Supply
        ("water tap is leaking in block a washroom", "Water Supply"),
        ("no water supply in the boys hostel restroom", "Water Supply"),
        ("drinking water filter is dirty and tastes bad", "Water Supply"),
        ("pipe burst in the hostel backyard causing flooding", "Water Supply"),
        ("clogged sink in the chemistry laboratory", "Water Supply"),
        ("toilet flush is not working in administrative floor", "Water Supply"),
        ("water pressure is too low in the canteen wash basin", "Water Supply"),
        ("no drinking water in the library cooler", "Water Supply"),
        ("water dispenser is serving hot water instead of cold", "Water Supply"),
        ("drainage water is overflowing in the garden area", "Water Supply"),
        ("water storage tank has algae and mud inside", "Water Supply"),
        ("plumbing issue in girls hostel ground floor washroom", "Water Supply"),
        ("no running water in the seminar hall washroom", "Water Supply"),
        ("taps are broken and water is continuously running", "Water Supply"),
        ("muddy water is coming out of the drinking water taps", "Water Supply"),
        ("water cooler pipe is rusted and leaking", "Water Supply"),
        ("canteen sink drain is completely blocked with waste", "Water Supply"),
        ("overhead water tank is overflowing and wasting water", "Water Supply"),
        ("no water in cafeteria wash basins", "Water Supply"),
        ("hostel washrooms have dry taps since morning", "Water Supply"),
        ("the sprinkler system is broken and flooding the path", "Water Supply"),
        ("clogged shower drains in hostel room block", "Water Supply"),
        ("rust colored water flowing in mechanical lab taps", "Water Supply"),
        ("sewage smell coming from the water pipelines", "Water Supply"),
        ("drinking water tap handle is broken off", "Water Supply"),
        ("water purifiers filter indicator is blinking red", "Water Supply"),
        ("no water for flushing in hostel block c", "Water Supply"),
        ("leakage in the main water supply pipeline near gate", "Water Supply"),
        ("well water supply pump is broken", "Water Supply"),
        ("inlet pipe of cooler has split and water is spraying", "Water Supply"),

        # Furniture
        ("broken bench in classroom 204", "Furniture"),
        ("chair leg is cracked and wobbling in the library", "Furniture"),
        ("the wooden desk in block c is split in half", "Furniture"),
        ("whiteboard holder is broken in class 303", "Furniture"),
        ("podium damaged in seminar hall, microphone stand broken", "Furniture"),
        ("table drawer is stuck in admin cabin", "Furniture"),
        ("wardrobe lock is broken in hostel room 12", "Furniture"),
        ("cupboard door fell off its hinges in staff room", "Furniture"),
        ("sofa cushion is torn in the visitors lobby", "Furniture"),
        ("shattered glass top on the office table", "Furniture"),
        ("metal frame of bench is bent and unsafe", "Furniture"),
        ("computer desk slider is broken in coding lab", "Furniture"),
        ("hostel cot frame is bent and squeaking loudly", "Furniture"),
        ("broken shelves in library computer section", "Furniture"),
        ("drawing boards are damaged in the civil engineering drawing hall", "Furniture"),
        ("auditorium seats are loose and coming off the floor", "Furniture"),
        ("dining tables in hostel canteen are wobbly", "Furniture"),
        ("broken cabinet glass door in lab 3", "Furniture"),
        ("notice board frame fell off the wall", "Furniture"),
        ("office chair height adjustment lever is broken", "Furniture"),
        ("broken laboratory stool legs", "Furniture"),
        ("teacher desk has missing panels", "Furniture"),
        ("classroom desk has sharp rusty nails sticking out", "Furniture"),
        ("broken book shelf racks in the central library", "Furniture"),
        ("plastic chairs in the seminar hall are cracked", "Furniture"),
        ("coat hanger in hostel room wardrobe is broken", "Furniture"),
        ("locker keys are stuck in the locker room cabinet", "Furniture"),
        ("benches in playground are broken and cracked", "Furniture"),
        ("examination hall desks are uneven and shaking", "Furniture"),
        ("wooden doors of classroom won't close properly due to warping", "Furniture"),

        # Laboratory
        ("microscope lens is scratched and blurry in biology lab", "Laboratory"),
        ("chemicals are out of stock in chemistry store room", "Laboratory"),
        ("digital oscilloscope is not turning on in circuits lab", "Laboratory"),
        ("bunsen burner is leaking gas in lab hall 2", "Laboratory"),
        ("multimeter is showing wrong reading and requires calibration", "Laboratory"),
        ("computers in programming lab are not booting up", "Laboratory"),
        ("soldering iron heater is broken and not heating up", "Laboratory"),
        ("mechanical lab lathe machine is jammed and vibrating", "Laboratory"),
        ("measuring cylinder and glass beakers are cracked", "Laboratory"),
        ("plc trainer kit is faulty in the automation lab", "Laboratory"),
        ("database server in database laboratory is down", "Laboratory"),
        ("software license has expired on lab computers", "Laboratory"),
        ("network switch in digital logic design lab is not working", "Laboratory"),
        ("pneumatic kit has air leaks in fluid mechanics lab", "Laboratory"),
        ("specimens in botany laboratory are damaged", "Laboratory"),
        ("distilled water maker in chemical lab is not functioning", "Laboratory"),
        ("welding machine in workshop is throwing error codes", "Laboratory"),
        ("cables are missing from microprocessor trainer kits", "Laboratory"),
        ("ventilation hood in organic chemistry lab has failed", "Laboratory"),
        ("c++ compiler not installed on computer number 15", "Laboratory"),
        ("lan cable is missing from system 24 in net lab", "Laboratory"),
        ("acid bottle cracked in store room, causing minor leak", "Laboratory"),
        ("ic tester is burnt and showing wrong chip tests", "Laboratory"),
        ("data structures lab systems lack keyboard keys", "Laboratory"),
        ("server rack in advanced computing lab is overheating", "Laboratory"),
        ("robotic arm controller not responding to commands", "Laboratory"),
        ("thermodynamics engine model is missing valves", "Laboratory"),
        ("autoclave machine in biotechnology lab isn't heating", "Laboratory"),
        ("projector screen in lab is stuck and won't roll down", "Laboratory"),
        ("lab components like resistors and capacitors are missing", "Laboratory"),

        # Hostel
        ("hostel room door lock is broken and won't lock", "Hostel"),
        ("window pane is shattered in room 210, hostel block b", "Hostel"),
        ("geyser in the girls hostel washroom is not heating water", "Hostel"),
        ("bed cot is broken and uncomfortable in room 15", "Hostel"),
        ("balcony sliding door is stuck and won't open", "Hostel"),
        ("curtain rod fell off the wall in room 305", "Hostel"),
        ("hostel lobby ceiling fan is making loud clicking sounds", "Hostel"),
        ("hostel mattress is stained and needs replacement", "Hostel"),
        ("lost wardrobe keys in room 112", "Hostel"),
        ("hostel common room tv remote is missing", "Hostel"),
        ("hostel wash basin is overflowing and flooding the hall", "Hostel"),
        ("stray dogs roaming inside girls hostel lobby", "Hostel"),
        ("hostel corridor is pitch dark due to fused tubes", "Hostel"),
        ("drinking water cooler in hostel floor 2 has warm water", "Hostel"),
        ("washing machine in hostel laundry room is not spinning", "Hostel"),
        ("warden office door lock jammed", "Hostel"),
        ("room heater in hostel is not working during winter", "Hostel"),
        ("bed bug infestation in hostel room 303 beds", "Hostel"),
        ("exhaust fan in hostel dining hall is jammed", "Hostel"),
        ("power supply cut off in only hostel block a", "Hostel"),
        ("ceiling leakage in hostel room 504 during rains", "Hostel"),
        ("hostel water pipes vibrating loudly when taps open", "Hostel"),
        ("study table in hostel room has collapsed", "Hostel"),
        ("hostel guest room fan regulator is broken", "Hostel"),
        ("hostel gate closes too early or lock is jammed", "Hostel"),
        ("no hot water supply in boys hostel showers", "Hostel"),
        ("hostel balcony drain is choked with leaves", "Hostel"),
        ("hostel elevator is stuck on third floor", "Hostel"),
        ("walls in hostel room 208 have paint peeling off due to dampness", "Hostel"),
        ("hostel induction stove in pantry is showing error", "Hostel"),

        # Transport
        ("college bus route 5 is late by an hour", "Transport"),
        ("ac bus heating system is not working", "Transport"),
        ("bus seat cover is torn and foam is coming out", "Transport"),
        ("college bus brake is making loud squeaking sound", "Transport"),
        ("bus driver is driving recklessly on route 12", "Transport"),
        ("bus pass card scanner is not reading cards", "Transport"),
        ("bus number 4 has a flat tyre near highway", "Transport"),
        ("window glass is vibrating and rattling in bus 15", "Transport"),
        ("shuttle bus frequency between campus gates is too low", "Transport"),
        ("college bus seat layout is too cramped", "Transport"),
        ("emergency door on college bus is jammed", "Transport"),
        ("bus conductor behaved rudely to students", "Transport"),
        ("bus engine is overheating and emitting smoke", "Transport"),
        ("college transport portal is not issuing new passes", "Transport"),
        ("rear view mirror of college bus is broken", "Transport"),
        ("college bus windshield has a big crack", "Transport"),
        ("gps tracking in college bus application is wrong", "Transport"),
        ("bus route 3 was cancelled without notification", "Transport"),
        ("oil leak noticed under college bus 8 in parking", "Transport"),
        ("bus wipers are not working during heavy rain", "Transport"),
        ("indicator lights on transport vehicles are broken", "Transport"),
        ("college bus horn is sounding constantly", "Transport"),
        ("seat belts are missing or broken in college van", "Transport"),
        ("college bus helper is not helping students board", "Transport"),
        ("dusty seats in college bus in the morning", "Transport"),
        ("wrong bus route assignment on transport card", "Transport"),
        ("bus speedometer is broken and not showing correct speed", "Transport"),
        ("transport supervisor office is closed during shift", "Transport"),
        ("ac bus vents are clogged and dusty", "Transport"),
        ("college ambulance has no oxygen cylinder backup", "Transport"),

        # Internet
        ("wifi connection is very slow in block a", "Internet"),
        ("cannot log in to the student portal on college wifi", "Internet"),
        ("wifi keeps disconnecting every 5 minutes in library", "Internet"),
        ("ethernet port is dead at desk number 4 in coding lab", "Internet"),
        ("no wifi signal strength in the hostel ground floor", "Internet"),
        ("router in class 402 is blinking red and has no network", "Internet"),
        ("slow internet speed in the main computer laboratory", "Internet"),
        ("cannot access the college library online website", "Internet"),
        ("dns server is not responding on college network", "Internet"),
        ("wifi network name ssid is not showing up in canteen", "Internet"),
        ("ip address conflict error on lab systems", "Internet"),
        ("internet link down in administrative department office", "Internet"),
        ("firewall blocking educational sites needed for project", "Internet"),
        ("wifi password is not working or credentials expired", "Internet"),
        ("unable to connect to campus wifi using student id", "Internet"),
        ("cisco router heating up and rebooting automatically", "Internet"),
        ("fiber optic cable damaged near block d construction site", "Internet"),
        ("e-learning portal moodle is slow and timing out", "Internet"),
        ("no internet connection in the girls hostel study hall", "Internet"),
        ("unable to upload files to cloud portal on college network", "Internet"),
        ("broadband speed drops to zero in afternoon", "Internet"),
        ("lan port socket in hostel room 103 is broken", "Internet"),
        ("college website shows security certificate error", "Internet"),
        ("proxy server error when accessing research journals", "Internet"),
        ("no internet access via lan switch in lab 4", "Internet"),
        ("hostel router has no power supply adapter", "Internet"),
        ("campus wifi registration page is not loading", "Internet"),
        ("slow download speed on college open wifi", "Internet"),
        ("cannot connect printer to network in administrative section", "Internet"),
        ("vpn server connection failed when working from home", "Internet"),

        # Cleaning
        ("trash can is overflowing in block b corridor", "Cleaning"),
        ("classroom floor is dirty with papers and chalk dust", "Cleaning"),
        ("washroom is smelling very bad and needs disinfectant", "Cleaning"),
        ("liquid spillage on the staircase of main building", "Cleaning"),
        ("thick dust layer on library shelves and reference books", "Cleaning"),
        ("spider webs all over the ceiling in class 104", "Cleaning"),
        ("litter and plastic bottles in college garden area", "Cleaning"),
        ("dirty and muddy steps in the entrance lobby", "Cleaning"),
        ("classroom whiteboard has permanent marker stains", "Cleaning"),
        ("hostel corridor is dusty and sweepers haven't come", "Cleaning"),
        ("food waste thrown around hostel canteen washbasin", "Cleaning"),
        ("dirty toilets with no soap in admin block", "Cleaning"),
        ("washroom mirrors are dirty and stained", "Cleaning"),
        ("leaves blocking the pathway in the courtyard", "Cleaning"),
        ("canteen tables are sticky and not cleaned after meals", "Cleaning"),
        ("academic block dustbins have no garbage bags inside", "Cleaning"),
        ("stray cat food leftovers rotting in the corridor", "Cleaning"),
        ("hostel balcony is full of dust and pigeon droppings", "Cleaning"),
        ("dirty windows in chemistry lab blocking sunlight", "Cleaning"),
        ("seminar hall carpets have stains and smell musty", "Cleaning"),
        ("floors are slippery because they were mopped without warning sign", "Cleaning"),
        ("water cooler drain pan is filled with slime and dirt", "Cleaning"),
        ("dirty sinks in the laboratory wash basins", "Cleaning"),
        ("dusty computer screens and keyboards in coding lab", "Cleaning"),
        ("pigeon nests and feathers in ventilator grills", "Cleaning"),
        ("canteen kitchen waste is piled up near eating tables", "Cleaning"),
        ("hostel toilet walls have spit stains", "Cleaning"),
        ("drinking water fountain basin is choked with tea bags", "Cleaning"),
        ("auditorium floor is sticky with spilled soft drinks", "Cleaning"),
        ("washroom floor is flooded with dirty toilet water", "Cleaning"),

        # Security
        ("strangers are entering the campus without id verification", "Security"),
        ("security guard is missing from the main entrance gate", "Security"),
        ("cctv camera in the parking lot is broken or facing wall", "Security"),
        ("parking lot lights are off, making it pitch dark", "Security"),
        ("girls hostel main gate lock is damaged and loose", "Security"),
        ("suspicious persons seen wandering near hostel at night", "Security"),
        ("mobile phone was stolen from classroom 302 desk", "Security"),
        ("bicycle was stolen from the cycle parking stand", "Security"),
        ("fire extinguisher in the laboratory has expired", "Security"),
        ("emergency exit door is locked or blocked with boxes", "Security"),
        ("college card reader at entrance gate is not working", "Security"),
        ("security guards not checking vehicle entry passes", "Security"),
        ("ragging incident or verbal abuse near cafeteria", "Security"),
        ("outsiders parking their cars in student parking zone", "Security"),
        ("cctv footage request is not being processed for theft case", "Security"),
        ("no female security guard present at girls hostel gate", "Security"),
        ("broken lock on emergency exit window in library", "Security"),
        ("security guard behaving rudely with college students", "Security"),
        ("stray animals entered campus and chasing students", "Security"),
        ("trespassing observed near college boundary wall", "Security"),
        ("valuable components stolen from engineering workshop", "Security"),
        ("broken security gate barrier in parking area", "Security"),
        ("fire alarm button cover is broken in computer science block", "Security"),
        ("suspicious bag left unattended near library stairs", "Security"),
        ("college entrance turnstiles are locked during rush hour", "Security"),
        ("theft of college properties from canteen fridge", "Security"),
        ("street lights in hostel path are dead, feels unsafe", "Security"),
        ("unauthorized event happening in seminar hall by outsiders", "Security"),
        ("broken glass pieces on basketball court poses hazard", "Security"),
        ("security guard sleeping during night duty at block a", "Security"),

        # Other
        ("exam schedule portal is not loading exam dates", "Other"),
        ("canteen food quality is sub-standard and unhygienic", "Other"),
        ("library book renewal portal is showing incorrect fines", "Other"),
        ("sports playground grass is uncut and needs maintenance", "Other"),
        ("request for reprinting college id card due to damage", "Other"),
        ("lost house keys in the cafeteria building", "Other"),
        ("tuition fee payment portal showing transaction failure", "Other"),
        ("admission form shows wrong spelling of student name", "Other"),
        ("gymnasium treadmills and weights are damaged", "Other"),
        ("feedback on seminar timings conflicts with classes", "Other"),
        ("college magazine submission portal is not working", "Other"),
        ("scholarship application verification is delayed by admin", "Other"),
        ("requesting permission to host coding club event", "Other"),
        ("college annual fest registration link is broken", "Other"),
        ("non-academic certificate not issued after completion", "Other"),
        ("canteen prices are higher than print mrp rates", "Other"),
        ("noise pollution from neighboring construction site", "Other"),
        ("request for sports kit issue for inter college match", "Other"),
        ("library card registration showing database mismatch", "Other"),
        ("request to change elective subject in semester portal", "Other"),
        ("canteen vendor behaving poorly with student customers", "Other"),
        ("college calendar shows incorrect holidays list", "Other"),
        ("delay in issuing grade sheets of last semester", "Other"),
        ("stationary shop on campus is closed during exams", "Other"),
        ("canteen drinking water cups are not available", "Other"),
        ("fees refund status has not updated since application", "Other"),
        ("canteen menu lacks vegetarian options", "Other"),
        ("no dustbins in auditorium lobby during events", "Other"),
        ("sports room indoor games carrom board is cracked", "Other"),
        ("request for parking pass activation sticker", "Other")
    ]

    # Split features (texts) and targets (categories)
    X = [item[0] for item in data]
    y = [item[1] for item in data]

    print(f"Training on {len(data)} sample complaints...")

    # Create TF-IDF + Naive Bayes pipeline
    model = make_pipeline(
        TfidfVectorizer(
            lowercase=True, 
            stop_words='english', 
            ngram_range=(1, 2),
            token_pattern=r'\b\w+\b'
        ),
        MultinomialNB(alpha=0.1)
    )

    # Fit pipeline
    model.fit(X, y)

    # Create output directory if it doesn't exist
    os.makedirs(os.path.dirname(os.path.abspath(__file__)), exist_ok=True)
    
    # Save the pipeline directly
    # joblib handles saving pipeline objects containing both the vectorizer and classifier
    model_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'model.joblib')
    joblib.dump(model, model_path)
    
    print(f"Model successfully trained and saved to {model_path}!")

if __name__ == "__main__":
    train()
